# Generated by Django 5.2.8 on 2025-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0003_inquiryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
