# Generated by Django 5.2.8 on 2025-12-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0006_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
